### ISSUE TITLE
Hyper seems to not import common.exceptions correctly

### ISSUE THREAD

**Issue by tyrelsouza** [Lukasa/hyper#114]
Ran the example from PyPi and it didn't work because of an exception not being imported correctly.

Traceback:
```
% python run.py
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from hyper import HTTP20Connection
  File "/Users/tyrelsouza/.virtualenvs/hyp/lib/python2.7/site-packages/hyper/__init__.py", line 11, in <module>
    from .http20.connection import HTTP20Connection
  File "/Users/tyrelsouza/.virtualenvs/hyp/lib/python2.7/site-packages/hyper/http20/connection.py", line 9, in <module>
    from ..common.exceptions import ConnectionResetError
ImportError: No module named common.exceptions
```

**Comment by Lukasa** [comment]
I believe this is fixed in v0.3.1.

Thanks for the report! :cake: :sparkles:
