### ISSUE TITLE
Hyper CLI tries to decode 'application/octet-stream' using utf-8 codec

### ISSUE THREAD

**Issue by direvius** [Lukasa/hyper#154]
Response headers:
```
HTTPHeaderMap([(b'content-type', b'application/octet-stream') ... etc ...
```
Exception:
```
Traceback (most recent call last):
  File "/usr/local/bin/hyper", line 9, in <module>
    load_entry_point('hyper==0.4.0', 'console_scripts', 'hyper')()
  File "/Users/direvius/git/hyper/hyper/cli.py", line 231, in main
    data = request(args)
  File "/Users/direvius/git/hyper/hyper/cli.py", line 222, in request
    data = response.read().decode(charset)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by Lukasa** [comment]
Fix now available in #156.
