### ISSUE TITLE
Hyper CLI AttributeError no attribute 'OP_NO_COMPRESSION'

### ISSUE THREAD

**Issue by schwartz1375** [Lukasa/hyper#192]
On Mac OS X 10.11.3, if I attempt to run the following:
$ hyper GET https://http2bin.org/
Traceback (most recent call last):
  File "/usr/local/bin/hyper", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/hyper/cli.py", line 244, in main
    data = request(args)
  File "/Library/Python/2.7/site-packages/hyper/cli.py", line 233, in request
    conn.request(args.method, args.url.path, args.body, args.headers)
  File "/Library/Python/2.7/site-packages/hyper/common/connection.py", line 98, in request
    method=method, url=url, body=body, headers=headers
  File "/Library/Python/2.7/site-packages/hyper/http11/connection.py", line 164, in request
    self.connect()
  File "/Library/Python/2.7/site-packages/hyper/http11/connection.py", line 128, in connect
    sock, proto = wrap_socket(sock, host, self.ssl_context)
  File "/Library/Python/2.7/site-packages/hyper/tls.py", line 36, in wrap_socket
    _context = init_context()
  File "/Library/Python/2.7/site-packages/hyper/tls.py", line 91, in init_context
    context.options |= ssl.OP_NO_COMPRESSION
AttributeError: 'module' object has no attribute 'OP_NO_COMPRESSION'

Given the error I did check that the command works as expected if  I don't use a HTTPS URL (example hyper GET http://http2bin.org/).

**Comment by Lukasa** [comment]
Your version of Python or OpenSSL is too old for us to safely secure the connection.

HTTP/2 puts some very strong requirements on the quality of the TLS used to establish the connection. One of these requirements is that TLS compression *must* be disabled. Your particular Python or OpenSSL does not expose `OP_NO_COMPRESSION`, which makes it impossible for hyper to disable it. Hyper correctly considers this an error condition: if it didn't, once the connection is established you'd likely see it immediately torn down with an INADEQUATE_SECURITY error code.

Where did your Python come from, and what OpenSSL is it linked against? (You can answer that latter question by typing `python -c 'import ssl; print ssl.OPENSSL_VERSION'`)

**Comment by schwartz1375** [comment]
Python came as Apple's development tools package (Python 2.7.10 (default, Oct 23 2015, 18:05:06) )
$ python -c 'import ssl; print ssl.OPENSSL_VERSION'
OpenSSL 0.9.8zg 14 July 2015

**Comment by Lukasa** [comment]
Yup, that version of OpenSSL is altogether too old to do HTTP/2. You'll need to replace it, probably using Homebrew.
