### ISSUE TITLE
Can't use example code

### ISSUE THREAD

**Issue by pkrolikowski** [Lukasa/hyper#198]
Hi,
The problem is that I can't run example code.
Platform:
- Ubuntu 14.04.2 LTS
- Python:  2.7.6 (default, Jun 22 2015, 17:58:13) \n[GCC 4.8.2]'

Steps to reproduce error:
 1. pip install git+https://github.com/Lukasa/hyper.git
 2. run example code: 
       from hyper import HTTPConnection
       conn = HTTPConnection('http2bin.org:443')
       conn.request('GET', '/get')
       resp = conn.get_response()
       print(resp.read())
Error:
krolikowskip@hyper-test-01:~/HTTP2$ python hyper_test.py
Traceback (most recent call last):
File "hyper_test.py", line 4, in <module>
conn.request('GET', '/get')
File "/usr/local/lib/python2.7/dist-packages/hyper/common/connection.py", line 98, in request
method=method, url=url, body=body, headers=headers
File "/usr/local/lib/python2.7/dist-packages/hyper/http11/connection.py", line 161, in request
self.connect()
File "/usr/local/lib/python2.7/dist-packages/hyper/http11/connection.py", line 121, in connect
sock, proto = wrap_socket(sock, host, self.ssl_context)
File "/usr/local/lib/python2.7/dist-packages/hyper/tls.py", line 36, in wrap_socket
_context = init_context()
File "/usr/local/lib/python2.7/dist-packages/hyper/tls.py", line 78, in init_context
context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
AttributeError: 'NoneType' object has no attribute 'SSLContext'

Import statement from compat.py hits ImportError exception because it can't load ssl_compat module (because of OpenSSL):
>>> import OpenSSL
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
from OpenSSL import rand, crypto, SSL
File "/usr/local/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>
from OpenSSL._util import (
File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in <module>
from cryptography.hazmat.bindings.openssl.binding import Binding
ImportError: No module named cryptography.hazmat.bindings.openssl.binding
>>>
Solution:
    apt-get install libffi-dev
    apt-get install libssl-dev
    pip install cryptography

Next try with example code returns error:  ImportError: No module named pyasn1_modules.rfc2459
Solution:
    apt-get install python-pyasn1-modules

Last problem: ImportError: No module named characteristic
Solution:
    pip install characteristic

Error handling will make things easer to debug, at least for me ;)

Regards.
PK

**Comment by Lukasa** [comment]
@pkrolikowski Thanks for the report!

The problems with `pyasn1_modules` and `characteristic` are unexpected: those should be resolved by the dependency tree, because I never import them from hyper. It seems that the PyOpenSSL you had is pretty severely broken. =(

I'm not sure how best to provide this debugging information: generally speaking hyper makes a best effort to get things to work on whatever platform it's being used on.
