### ISSUE TITLE
Hyper should not be trying to RST all the streams if it receives a GOAWAY

### ISSUE THREAD

**Issue by greencoder** [Lukasa/hyper#244]
@Lukasa asked me to open the issue for this traceback I received today:

```
Traceback (most recent call last):
  File "/home/snewman/.Envs/propeller/lib/python3.4/site-packages/h2/connection.py", line 225, in process_input
    func, target_state = self._transitions[(self.state, input_)]
KeyError: (<ConnectionState.CLOSED: 3>, <ConnectionInputs.SEND_RST_STREAM: 7>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/snewman/code/propellerapp.net/worker.py", line 103, in <module>
    result_code = client.send_notification(token, payload, topic=args.topic)
  File "/home/snewman/code/propellerapp.net/apns2/client.py", line 43, in send_notification
    response = self.__connection.get_response(stream_id)
  File "/home/snewman/.Envs/propeller/lib/python3.4/site-packages/hyper/http20/connection.py", line 293, in get_response
    return HTTP20Response(stream.getheaders(), stream)
  File "/home/snewman/.Envs/propeller/lib/python3.4/site-packages/hyper/http20/stream.py", line 219, in getheaders
    self._recv_cb(stream_id=self.stream_id)
  File "/home/snewman/.Envs/propeller/lib/python3.4/site-packages/hyper/http20/connection.py", line 752, in _recv_cb
    self._single_read()
  File "/home/snewman/.Envs/propeller/lib/python3.4/site-packages/hyper/http20/connection.py", line 682, in _single_read
    self.close()
  File "/home/snewman/.Envs/propeller/lib/python3.4/site-packages/hyper/http20/connection.py", line 422, in close
    stream.close(error_code)
  File "/home/snewman/.Envs/propeller/lib/python3.4/site-packages/hyper/http20/stream.py", line 278, in close
    self._conn.reset_stream(self.stream_id, error_code or 0)
  File "/home/snewman/.Envs/propeller/lib/python3.4/site-packages/h2/connection.py", line 856, in reset_stream
    self.state_machine.process_input(ConnectionInputs.SEND_RST_STREAM)
  File "/home/snewman/.Envs/propeller/lib/python3.4/site-packages/h2/connection.py", line 230, in process_input
    "Invalid input %s in state %s" % (input_, old_state)
h2.exceptions.ProtocolError: Invalid input ConnectionInputs.SEND_RST_STREAM in state ConnectionState.CLOSED
```

**Comment by Lukasa** [comment]
Hey!

So this issue is basically down to the fact that hyper is receiving a GOAWAY and then trying to close each stream in turn by RST_STREAMing. Either it shouldn't do that, or streams should tolerate the attempt to reset them if you can't actually do it.

Definitely a bug though!
