### ISSUE TITLE
WINDOW_UPDATE after stream closed when (filesize + max frame size) >= window size

### ISSUE THREAD

**Issue by ant1441** [Lukasa/hyper#260]
The following code:

``` python
from hyper import HTTPConnection

conn = HTTPConnection('http2bin.org:443')
conn.request('GET', '/bytes/49180')
resp = conn.get_response()

print(len(resp.read()))
```

Throws this exception:

```python
/tmp/tst$ python test.py 
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    print(resp.read())
  File "/tmp/tst/env/lib/python3.5/site-packages/hyper-0.7.0.dev0-py3.5.egg/hyper/http20/response.py", line 116, in read
    data = b''.join([self._data_buffer, self._stream._read()])
  File "/tmp/tst/env/lib/python3.5/site-packages/hyper-0.7.0.dev0-py3.5.egg/hyper/http20/stream.py", line 139, in _read
    self._recv_cb(stream_id=self.stream_id)
  File "/tmp/tst/env/lib/python3.5/site-packages/hyper-0.7.0.dev0-py3.5.egg/hyper/http20/connection.py", line 760, in _recv_cb
    self._single_read()
  File "/tmp/tst/env/lib/python3.5/site-packages/hyper-0.7.0.dev0-py3.5.egg/hyper/http20/connection.py", line 659, in _single_read
    self.streams[event.stream_id].receive_data(event)
  File "/tmp/tst/env/lib/python3.5/site-packages/hyper-0.7.0.dev0-py3.5.egg/hyper/http20/stream.py", line 192, in receive_data
    increment, stream_id=self.stream_id
  File "/tmp/tst/env/lib/python3.5/site-packages/h2-2.4.0-py3.5.egg/h2/connection.py", line 821, in increment_flow_control_window
  File "/tmp/tst/env/lib/python3.5/site-packages/h2-2.4.0-py3.5.egg/h2/stream.py", line 852, in increase_flow_control_window
  File "/tmp/tst/env/lib/python3.5/site-packages/h2-2.4.0-py3.5.egg/h2/stream.py", line 118, in process_input
  File "/tmp/tst/env/lib/python3.5/site-packages/h2-2.4.0-py3.5.egg/h2/stream.py", line 298, in send_on_closed_stream
h2.exceptions.StreamClosedError: 1
```

Following (a similar) request in Wireshark I saw the following things happen:
(The Wireshark trace for the request to http2bin does not appear to be correct to me)

* The client sends a SETTINGS frame with :
  * Initial Windows size : 65535
  * Max frame size : 16384
* The server sends several DATA frames containing the entire payload
* The server sends a DATA frame containing 0 data, with a END STREAM flag
* The client sends a WINDOW_UPDATE frame to increase the window size

It appears that this final WINDOW_UPDATE is causing an error due to it being sent when the stream has been closed.
I assume that hyper is attempting to increase the window size to allow for a further frame of size "Max frame size" while not going over the window size.

However I'm not clear on why this is causing a client exception, or why, if the client is throwing a StreamClosedError the WINDOW_UPDATE frame still goes out on the wire.
Or is the Exception occurring because the server has closed the connection after receiving a frame for a closed stream?

**Comment by Lukasa** [comment]
Yeah, hyper-h2 disallows window update frames on closed streams. The WINDOW_UPDATE isn't going out on the wire: normally we'd have to emit two. 

The fix here, probably, is to update to rely on hyper-h2 2.4.0, and then use the related events properties to make sure we don't do this unnecessarily.
