### ISSUE TITLE
First example from docs fails

### ISSUE THREAD

**Issue by r0fls** [Lukasa/hyper#308]
This fails due to time out in python 2 and 3:

```python
from hyper import HTTPConnection

conn = HTTPConnection('http2bin.org:443')
conn.request('GET', '/get')
resp = conn.get_response()

print(resp.read())
```

It also fails when I try with the hyper-h2 server example (included below). It causes the server to produce the below:

```
Traceback (most recent call last):
  File "h2test.py", line 45, in <module>
    handle(sock.accept()[0])
  File "h2test.py", line 19, in handle
    events = conn.receive_data(data)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/h2/connection.py", line 1443, in receive_data
    self.incoming_buffer.add_data(data)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/h2/frame_buffer.py", line 52, in add_data
    raise ProtocolError("Invalid HTTP/2 preamble.")
h2.exceptions.ProtocolError: Invalid HTTP/2 preamble.
```

For that test I used this:

```python
from hyper import HTTPConnection

conn = HTTPConnection(host='localhost', port=8000)
conn.request('GET', '/get')
resp = conn.get_response()

print(resp.read())
```

**hyper-h2 server**
```python
import socket
import h2.connection

sock = socket.socket()
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
sock.bind(('0.0.0.0', 8000))
sock.listen(5)

def handle(sock):
    conn = h2.connection.H2Connection(client_side=False)
    conn.initiate_connection()
    sock.sendall(conn.data_to_send())

    while True:
        data = sock.recv(65535)
        if not data:
            break

        events = conn.receive_data(data)
        for event in events:
            if isinstance(event, h2.events.RequestReceived):
                send_response(conn, event)

        data_to_send = conn.data_to_send()
        if data_to_send:
            sock.sendall(data_to_send)


def send_response(conn, event):
    stream_id = event.stream_id
    conn.send_headers(
        stream_id=stream_id,
        headers=[
            (':status', '200'),
            ('server', 'basic-h2-server/1.0')
        ],
    )
    conn.send_data(
        stream_id=stream_id,
        data=b'ok',
        end_stream=True
    )

while True:
    handle(sock.accept()[0])
```

Any help is appreciated. I tried with python 3.5 and 2.7. Here is the hyper/hyper-h2 version info:

```
>>> hyper.__version__
'0.7.0'
>>> import h2
>>> h2.__version__
'2.5.2'
```

**Comment by Lukasa** [comment]
The problem with the first example is that `http2bin.org` is...uh...resting.

![Parrot Sketch](https://static4.businessinsider.com/image/47ff8e9314b9b95600bbe811-506-253/sonopia-founder-virtual-carrier-not-dead-just-resting.jpg)

So `http2bin.org` was hosted on Carina, which recently got all messy, and I haven't had a chance to rebuild it in any way. So right now the server just times out.

As to your other test, hyper-h2 *only* speaks HTTP/2, whereas hyper speaks both. When you use a `HTTPConnection` object like that, it attempts to negotiate HTTP/2. The TL;DR here is that because you're not using TLS, hyper tries to negotiate by sending a HTTP/1.1 request with an Upgrade header, which hyper-h2 doesn't understand.

You can fix it by changing to use `HTTP20Connection` instead of `HTTPConnection`, which will just immediately leap into doing HTTP/2.
