### ISSUE TITLE
PROTOCOL_ERROR occurred when accessing twitter.com

### ISSUE THREAD

**Issue by t2y** [Lukasa/hyper#84]
As described in [comments in pull/82](https://github.com/Lukasa/hyper/pull/82#issuecomment-73263780), for some reason, I tried to GET twitter.com, but `PROTOCOL_ERROR` occurred as below.

```sh
$ hyper --debug https://twitter.com
url info: {'scheme': 'https', 'host': 'twitter.com', 'port': 443, 'path': '/', 'query': None, 'netloc': 'twitter.com', 'fragment': None}
Commandline Argument: Namespace(_url='https://twitter.com', body=None, debug=True, headers={}, items=[], method='GET', url=<hyper.cli.set_url_info.<locals>.UrlInfo object at 0x10761e5c0>)
Sending frame SettingsFrame on stream 0
Received frame SettingsFrame on stream 0
Sending frame SettingsFrame on stream 0
HPACK encoding [(':method', 'GET'), (':scheme', 'https'), (':authority', 'twitter.com'), (':path', '/')]
Adding (b':method', b'GET') to the header table
Encoding 2 with 7 bits.
Adding (b':scheme', b'https') to the header table
Encoding 7 with 7 bits.
Adding (b':authority', b'twitter.com') to the header table
Encoding 1 with 4 bits.
Encoding 8 with 7 bits.
Adding (b':path', b'/') to the header table
Encoding 4 with 7 bits.
Encoded header block to b'\x82\x87\x01\x88O\x83%%\xb1r\x1e\x9f\x84'
Sending frame HeadersFrame on stream 1
Received frame GoAwayFrame on stream 0
Traceback (most recent call last):
  File "/Users/t2y/.virtualenvs/hyper/bin/hyper", line 9, in <module>
    load_entry_point('hyper==0.2.0', 'console_scripts', 'hyper')()
  File "/path/to/hyper/hyper/cli.py", line 227, in main
    print(request(args))
  File "/path/to/hyper/hyper/cli.py", line 215, in request
    response = conn.getresponse()
  File "/path/to/hyper/hyper/http20/connection.py", line 171, in getresponse
    return HTTP20Response(stream.getheaders(), stream)
  File "/path/to/hyper/hyper/http20/stream.py", line 293, in getheaders
    self._recv_cb()
  File "/path/to/hyper/hyper/http20/connection.py", line 580, in _recv_cb
    self._consume_single_frame()
  File "/path/to/hyper/hyper/http20/connection.py", line 500, in _consume_single_frame
    self._consume_frame_payload(frame, data)
  File "/path/to/hyper/hyper/http20/connection.py", line 566, in _consume_frame_payload
    self.receive_frame(frame)
  File "/path/to/hyper/hyper/http20/connection.py", line 372, in receive_frame
    (frame.error_code, frame.additional_data)
hyper.http20.exceptions.ConnectionError: Encountered error 1, extra data b''.
```

Removing `ENABLE_PUSH` in the setting frame makes it work. 

```diff
diff --git a/hyper/http20/connection.py b/hyper/http20/connection.py
index 659be5f..1d146a8 100644
--- a/hyper/http20/connection.py
+++ b/hyper/http20/connection.py
@@ -208,7 +208,6 @@ class HTTP20Connection(object):
             # connection, followed by an initial settings frame.
             sock.send(b'PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n')
             f = SettingsFrame(0)
-            f.settings[SettingsFrame.ENABLE_PUSH] = int(self._enable_push)
             self._send_cb(f)
 
             # The server will also send an initial settings frame, so get it.
```

I couldn't find [http2-17 spec](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17) about why sending `ENABLE_PUSH` causes an error. And then, on other sites, for example https://nghttp2.org/, it works well. I wonder if there's something wrong on server side in twitter.com. I don't know how to inform an issue to twitter.com. So, I just file this as an information for new users.

**Comment by Lukasa** [comment]
This is a known error in twitter.com. Somewhat appropriately I filed this as a bug report [via Twitter](https://twitter.com/Lukasaoz/status/563771664576811008).

Thanks for the update @t2y! This will be a good resource for others, but for now I'll be closing this as it's not a hyper bug. =)

**Comment by t2y** [comment]
Oh, you already reported to twitter via twitter. Thank you!
